### ISSUE TITLE
Connot find module

### ISSUE THREAD

**Issue by patryck507** [JoshTheDuck/csgo-commend-bot#4]
```
node index.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './helpers/Target.js'
Require stack:
- C:\Users\Lukas\Desktop\csgo-commend-bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Lukas\Desktop\csgo-commend-bot-master\index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Lukas\\Desktop\\csgo-commend-bot-master\\index.js' ]
}
```

**Comment by Musta40** [comment]
Is it commend bot up and running again? Or its still off guys?

**Comment by FedericoCurzel** [comment]
Hi! Could you solve the problem? I get a similar one and I cannot solve it... 

internal/modules/cjs/loader.js:883 throw err; ^

Error: Cannot find module 'C:\Users\Laboratoire fNIRS\node_modules\ijavascript\lib\kernel.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
